### ISSUE TITLE
 jp.maio.sdk.android.s.getVisibility() on a null object reference

### ISSUE THREAD

**Issue by jackyhieu** [imobile-maio/maio-Android-SDK#21]
java.lang.NullPointerException: Attempt to invoke virtual method 'int 
      jp.maio.sdk.android.s.getVisibility()' on a null object reference
        at jp.maio.sdk.android.HtmlBasedAdActivity$2.run(Unknown Source:18)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

I open video and click backhardkey of device. wait 3s. App crash and show error above

**Comment by im-ade** [comment]
@jackyhieu thank you for the report, we are aware of the issue and are creating a patch for it. The patch will be out in the next few days.

**Comment by jackyhieu** [comment]
@im-ade thank you. I will wait.

**Comment by jackyhieu** [comment]
This bug has been resolved on version 1.1.6
