### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String         java.io.File.getPath()' on a null object reference

### ISSUE THREAD

**Issue by jackyhieu** [imobile-maio/maio-Android-SDK#23]
## どういう問題が発生するか

       11-14 10:19:16.283 22832-22832/packagename E/AndroidRuntime: FATAL EXCEPTION: main
       Process: jp.seesaa.rino.development, PID: 22832
        java.lang.RuntimeException: Unable to start activity 
       ComponentInfo{packagename/jp.maio.sdk.android.HtmlBasedAdActivity}:  
       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 
       java.io.File.getPath()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String 
       java.io.File.getPath()' on a null object reference
        at jp.maio.sdk.android.a.a(Unknown Source)
        at jp.maio.sdk.android.HtmlBasedAdActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:5933)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
        at android.app.ActivityThread.access$800(ActivityThread.java:144) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5221) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 

### maio Android SDK Version
v1.1.6

### Android Version

(e.g. 5.0.2 )

### Device

(HTC Nexus 9 5.0.2)

**Comment by im-ade** [comment]
Closing issue because its been fixed in latest release
